name: Lint, Test & Docker Build

on:
  push:
    branches: [ "**" ]
    paths:
      - "**.py"
      - Dockerfile

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run pylint
      run: pylint *.py

    - name: Run unit tests
      run: python -m unittest discover

    - name: Build Docker image
      run: docker build -t my-python-app .
